before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
main:
  tags:
    - shell
  script:
    - docker build -t ostrich .
    - docker run --rm --entrypoint /opt/ostrich/build/ostrich_test ostrich
doc:
  before_script:
    - apt-get update
    - apt-get install -y doxygen
  script:
    - doxygen
  artifacts:
    paths:
      - doc